logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: TRACE
    web: INFO

spring:
  mvc:
    log-request-details: true

  security:
    oauth2:
      client:
        registration:
          demo1:
            client-id: spring-bug-1
            client-secret: spring-bug-1
            authorizationGrantType: authorization_code
            redirect-uri: "https://127.0.0.1:8443/login/oauth2/code/{registrationId}"
            scope: openid
          demo2:
            client-id: spring-bug-2
            client-secret: spring-bug-2
            authorizationGrantType: authorization_code
            redirect-uri: "https://127.0.0.1:8443/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          demo1:
            issuer-uri: http://localhost:9000
          demo2:
            issuer-uri: http://localhost:9000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  jackson:
    default-property-inclusion: non_empty

management:
  info:
    java:
      enabled: true
server:
  port: 8443
  ssl:
    key-alias: localhost
    key-store:  localhost.p12
    key-store-password: spring
    key-password: spring
  servlet:
    session:
      timeout: 15m

